/run/initialize
/vis/open OGL
#/vis/viewer/set/viewpointVector 1.9 0.3 1.5
/vis/viewer/set/viewpointVector -1 -0.2 0.2
/vis/viewer/set/upVector 0 1 0
#/vis/viewer/set/viewpointVector 2.0 0.0 0.0
/vis/viewer/set/lightsVector -1 0 0
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
#/vis/scene/add/scale 5 cm
/vis/scene/add/axes
/vis/scene/add/eventID
#/vis/reviewKeptEvents
/vis/viewer/zoom 1.7
/vis/scene/endOfEventAction accumulate
/vis/viewer/flush
